import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!; const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ZOHO_CLIENT_ID=Deno.env.get("ZOHO_CLIENT_ID")||"", ZOHO_CLIENT_SECRET=Deno.env.get("ZOHO_CLIENT_SECRET")||"", ZOHO_REFRESH_TOKEN=Deno.env.get("ZOHO_REFRESH_TOKEN")||"";
const ZOHO_ACCOUNTS_DOMAIN=Deno.env.get("ZOHO_ACCOUNTS_DOMAIN")||"https://accounts.zoho.com", ZOHO_MAIL_DOMAIN=Deno.env.get("ZOHO_MAIL_DOMAIN")||"https://mail.zoho.com";
const WEBHOOK_SECRET=Deno.env.get("ZOHO_WEBHOOK_SECRET")||""; const db=createClient(SUPABASE_URL,SERVICE_ROLE_KEY);
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json"}});
const norm=(v:unknown)=>String(v??"").normalize("NFKC").toUpperCase().replace(/\s+/g," ").trim();
async function token(){if(!ZOHO_CLIENT_ID||!ZOHO_CLIENT_SECRET||!ZOHO_REFRESH_TOKEN)throw new Error("Zoho OAuth secrets are not configured");const b=new URLSearchParams({refresh_token:ZOHO_REFRESH_TOKEN,client_id:ZOHO_CLIENT_ID,client_secret:ZOHO_CLIENT_SECRET,grant_type:"refresh_token"});const r=await fetch(`${ZOHO_ACCOUNTS_DOMAIN}/oauth/v2/token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:b});const j=await r.json();if(!r.ok||!j.access_token)throw new Error(`Zoho token error: ${JSON.stringify(j)}`);return j.access_token;}
async function zget(path:string,t:string,accept="application/json"){const r=await fetch(`${ZOHO_MAIL_DOMAIN}${path}`,{headers:{Accept:accept,Authorization:`Zoho-oauthtoken ${t}`}});if(!r.ok){const tx=await r.text();throw new Error(`Zoho ${r.status}: ${tx.slice(0,800)}`)}return r;}
async function account(t:string){const r=await zget('/api/accounts',t);const j=await r.json();const a=(j?.data||[]).find((x:any)=>x.primaryEmailAddress==='business@qawafialharamainiq.com'||x.emailAddress==='business@qawafialharamainiq.com')||(j?.data||[])[0];if(!a)throw new Error('Zoho account not found');return String(a.accountId??a.account_id??a.id)}
async function inbox(t:string,a:string){const fr=await zget(`/api/accounts/${a}/folders`,t);const j=await fr.json();const f=(j?.data||[]).find((x:any)=>x.folderType==='Inbox'||x.folderName==='Inbox');if(!f)throw new Error('Zoho Inbox folder not found');return String(f.folderId)}
async function mails(t:string,a:string,f:string){const r=await zget(`/api/accounts/${a}/messages/view?folderId=${encodeURIComponent(f)}&start=1&limit=20&status=all&sortBy=date&sortorder=false&attachedMails=true&includeto=true`,t);const j=await r.json();return j?.data||[]}
function strip(s:string){return s.replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
async function findMatch(text:string){const n=norm(text);const {data}=await db.from('pilgrims').select('id,full_name,passport_number,passport_first_name,nationality').limit(5000);const arr=data||[];const pass=(n.match(/\b[A-Z]{1,3}[0-9]{5,12}\b/)||[])[0]||'';if(pass){const p=arr.find((x:any)=>norm(x.passport_number)===pass);if(p)return {p,method:'passport',confidence:1}}
const exact=arr.filter((p:any)=>{const name=norm(p.full_name),first=norm(p.passport_first_name);return (name.length>4&&n.includes(name))||(first&&first.length>3&&n.includes(first))});
if(exact.length===1)return {p:exact[0],method:'name',confidence:.9}; return {p:null,method:'unmatched',confidence:0}}
async function processMessage(t:string,a:string,f:string,m:any){const mid=String(m.messageId||m.message_id||'');if(!mid)return null;const subject=String(m.subject||'');const sender=String(m.fromAddress||m.sender||'');const ct=await zget(`/api/accounts/${a}/folders/${f}/messages/${mid}/content`,t);const cj=await ct.json();const body=strip(String(cj?.data?.content||''));const ai=await zget(`/api/accounts/${a}/folders/${f}/messages/${mid}/attachmentinfo?includeInline=false`,t);const aj=await ai.json();const atts=aj?.data?.attachments||[];const pdf=atts.find((x:any)=>/\.pdf$/i.test(String(x.attachmentName||'')))||atts[0];if(!pdf)return {messageId:mid,status:'no_pdf'};
const text=`${subject}\n${sender}\n${body}\n${pdf.attachmentName||''}`;const match=await findMatch(text);let status='unmatched',path=null;
if(match.p){const ar=await zget(`/api/accounts/${a}/folders/${f}/messages/${mid}/attachments/${pdf.attachmentId}`,t,'application/octet-stream');const bytes=new Uint8Array(await ar.arrayBuffer());path=`visa-email-${match.p.id}-${Date.now()}.pdf`;const up=await db.storage.from('pilgrim-photos').upload(path,bytes,{upsert:false,contentType:'application/pdf'});if(up.error)throw up.error;const today=new Date().toISOString().slice(0,10);const ur=await db.from('pilgrims').update({visa_document_path:path,visa_status:'issued',visa_issued_at:today}).eq('id',match.p.id);if(ur.error)throw ur.error;status='matched_saved';}
await db.from('visa_email_events').insert({provider:'zoho',message_id:mid,sender,subject,received_at:m.receivedTime?new Date(Number(m.receivedTime)).toISOString():new Date().toISOString(),attachment_name:pdf.attachmentName||null,attachment_id:String(pdf.attachmentId||''),matched_pilgrim_id:match.p?.id||null,match_method:match.method,match_confidence:match.confidence,status,error_message:null});
return {messageId:mid,attachment:pdf.attachmentName,matched:!!match.p,status,pilgrim_id:match.p?.id||null};}
async function runSync(){const t=await token(),a=await account(t),f=await inbox(t,a),ms=await mails(t,a,f);const out=[];for(const m of ms.slice(0,10)){try{out.push(await processMessage(t,a,f,m))}catch(e){out.push({messageId:m.messageId,status:'error',error:String(e)})}}await db.from('zoho_mail_integration').update({connected:true,account_id:a,folder_id:f,last_sync_at:new Date().toISOString(),last_message_id:ms[0]?.messageId||null,updated_at:new Date().toISOString()}).eq('email_address','business@qawafialharamainiq.com');return {ok:true,processed:out};}
Deno.serve(async(req)=>{try{const u=new URL(req.url);if(req.method==='GET')return json({ok:true,service:'zoho-visa-mail',email:'business@qawafialharamainiq.com',configured:!!(ZOHO_CLIENT_ID&&ZOHO_CLIENT_SECRET&&ZOHO_REFRESH_TOKEN),webhook:`${u.origin}?action=webhook`,sync:`${u.origin}?action=sync`});if(req.method==='POST'&&u.searchParams.get('action')==='webhook'){if(WEBHOOK_SECRET&&((req.headers.get('x-qawafel-webhook-secret')||u.searchParams.get('secret'))!==WEBHOOK_SECRET))return json({error:'Unauthorized'},401);const p=await req.json().catch(()=>({}));const event=p?.data?.[0]||p?.data||p?.mail||p;const subject=String(event?.subject||'');const sender=String(event?.from||event?.fromAddress||event?.sender||'');const mid=event?.messageId||event?.message_id||event?.id;const {data}=await db.from('visa_email_events').select('id').eq('message_id',mid?String(mid):'__none__').limit(1);if(data?.length)return json({ok:true,duplicate:true});
if(!ZOHO_CLIENT_ID||!ZOHO_CLIENT_SECRET||!ZOHO_REFRESH_TOKEN)return json({ok:true,queued:true,reason:'Zoho OAuth not configured yet',subject,sender,message_id:mid||null});
const result=await runSync();return json({ok:true,triggered:true,subject,sender,message_id:mid||null,result});}
if(req.method==='POST'&&u.searchParams.get('action')==='sync')return json(await runSync());return json({error:'Use POST ?action=webhook or ?action=sync'},400)}catch(e){console.error(e);return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
